### ISSUE TITLE
Scavenger doesn't wait for element with ID before triggering promise

### ISSUE THREAD

**Issue by tiagosiebler** [pietrovismara/scavenger#2]
I'm trying out scavenger to scrape search results from a dynamically populated web page. I saw that the selector parameter can be used to wait for an element with ID before continuing, which is perfect for waiting for a search to finish. Yet I'm seeing the result before the JS populated the page:
```
	var url = 'https://lw.microstrategy.com/msdz/MSDL/GARelease_Current/docs/projects/WebSDK/default.htm#search-test';
	scavenger.scrape(url, {    
	    selector: '#resultList', // ID of a DOMElement to wait before scraping 
	    minify: false, // If true, minify the html 
	})
	.then((html) => {
		console.log("html: ",html);
	});
```

This line in the returned HTML:

`<h1 id="results-heading">Your search for <span class="query"></span> returned <span class="total-results"></span> result(s).</h1>
`
Should be:
`<h1 id="results-heading">Your search for <span class="query">"test"</span> returned <span class="total-results">49</span> result(s).</h1>
`
Am I using this wrong? Thanks!

**Comment by pietrovismara** [comment]
It looks like you are using it right. I'm going to test your URL with that
selector and i will let you know asap.

Il ven 30 giu 2017, 5:44 PM Tiago <notifications@github.com> ha scritto:

**Comment by pietrovismara** [comment]
There was a bug with the selector but it's fixed now. You can update to version `3.2.3`.

This is a screenshot made by scavenger of your URL with version `3.2.3`:

![image](https://user-images.githubusercontent.com/9806520/27747559-fa44ded4-5dcb-11e7-8946-ca01217cd82a.png)
