### ISSUE TITLE
Passing options to nightmareJS

### ISSUE THREAD

**Issue by lisandro52** [pietrovismara/scavenger#3]
Hi! Is there anyway we could pass options down to NightmareJS?  I'm specifically looking for an option to avoid loading images from the page.

Thanks!

**Comment by pietrovismara** [comment]
Hi! There wasn't any way, until this morning. I just implemented it 'cause it seems a good idea. Already pushed on github and on npm, release 3.3.0.

So you can now pass the options for Nightmare in this way (this options would block images loading, as you asked in the issue).

```javascript
scavenger.scrape(url, {
    nightmareOptions: {
        webPreferences: {
            images: false
        }
    }
})
```

Thanks for the feedback, and please leave a star if you're enjoying scavenger.

**Comment by lisandro52** [comment]
This right here is what I love from OSS. Thank you, I'll test it out tonight.
