### ISSUE TITLE
minimalist example working?

### ISSUE THREAD

**Issue by idkjs** [pietrovismara/scavenger#5]
installed with npm i scavenger.  Created the following file.

```js
const scavenger = require('scavenger');

scavenger.scrape("https://reddit.com")
.then((html) => {})
```

This runs then outputs nothing to the console.  Is this expected?

**Comment by idkjs** [comment]
Look like this works if you log to console per example later down in readme.

```js
scavenger.scrape("https://reddit.com").then(html => {
  console.log(html);
});
```

**Comment by pietrovismara** [comment]
Yes, i guess my example is so minimal that it doesn't show any output, although it is actually working :+1:

**Comment by idkjs** [comment]
Trying to get this to work on an angular example like http://visa.lafrenchtech.com/10/find-your-future-employer-in-france-french-tech-visa. Have any angular scrape code sitting around? It was easy enough to get the data but I wanted to do it programmatically.

**Comment by pietrovismara** [comment]
You can check the [examples](https://github.com/pietrovismara/scavenger/blob/master/examples/extract.md) to see how .extract works.

I also published a [post on medium](https://medium.com/@pp.vismara/scraping-the-web-series-18100d8603ad) with some more example.

When scraping single page applications like websites built with angular, you might also want to check the `selector` option, which allows you to wait for a DOMElement to be rendered before starting to scrape. Check it on the [repository home page](https://github.com/pietrovismara/scavenger).
